### ISSUE TITLE
NewContact throws MalformedResponseDataException on successful contact creation

### ISSUE THREAD

**Issue by Galyam** [GetResponse/sdk-php#16]
NewContact throws MalformedResponseDataException on successful contact creation
'Invalid JSON: Syntax error (4) Data: '

Stack trace:
#0 vendor/getresponse/sdk-php-client/src/Operation/SuccessfulOperationResponse.php(70): Getresponse\Sdk\Client\Exception\MalformedResponseDataException::createFromJsonLastErrorMsg('')
#1 vendor/getresponse/sdk-php-client/src/Operation/SuccessfulOperationResponse.php(57): Getresponse\Sdk\Client\Operation\SuccessfulOperationResponse->decodeJson('')
#2 commands/GetResponseController.php(59): Getresponse\Sdk\Client\Operation\SuccessfulOperationResponse->getData()

however i need to get contact id

indeed, the response from the server comes empty
class GuzzleHttp\Psr7\Stream#47 (7) {
  private $stream =>
  resource(176) of type (stream)
  private $size =>
  NULL
  private $seekable =>
  bool(true)
  private $readable =>
  bool(true)
  private $writable =>
  bool(true)
  private $uri =>
  string(10) "php://temp"
  private $customMetadata =>
  array(0) {
  }
}

**Comment by maciejtarnowski** [comment]
Hi @Galyam,

[Adding contacts](https://apireference.getresponse.com/#operation/createContact) is an asynchronous operation, and the API returns an empty `202 Accepted` response on success. The successful response does not necessarily mean that the contact will be added - it might get rejected later in the process. That's why we are not able to return an ID at that point. To get the ID, you can use [callbacks](https://apidocs.getresponse.com/v3/callbacks/subscribe) or [query the API](https://apireference.getresponse.com/#operation/getContactList) using `email` and `campaignId` filters after some time.

**Comment by Galyam** [comment]
so why is an exception thrown then?

**Comment by maciejtarnowski** [comment]
The exception is thrown because you're calling `getData()` method, and there is no data in the response. We'll think about a solution for that, but I guess all we will be able to do is throw a more meaningful exception. For now, make sure to not call `getData()` on responses for operations that have them empty (return `202 Accepted` or `204 No content`) and use only `isSuccess()` method to check the result.

**Comment by Galyam** [comment]
This is what a function call looks like, just this:

`try {`
`$operation = new CreateContact($newContact); `
`$response = $client->call($operation);`
`} catch (\Exception $e) {`
` `
`}`

**Comment by maciejtarnowski** [comment]
I'm sorry, but I still can't replicate the issue you're having.

This is how I tried to do that:
```php
<?php

use Getresponse\Sdk\GetresponseClientFactory;
use Getresponse\Sdk\Operation\Contacts\CreateContact\CreateContact;
use Getresponse\Sdk\Operation\Model\CampaignReference;
use Getresponse\Sdk\Operation\Model\NewContact;

require_once __DIR__ . '/../vendor/autoload.php';

$client = GetresponseClientFactory::createWithApiKey(getenv('API_KEY'));

$addContact = new CreateContact(
    new NewContact(
        new CampaignReference('abc123'),
        'redacted@example.com'
    )
);

try {
    $response = $client->call($addContact);
} catch (\Exception $e) {
    var_dump($response);
}
```

With or without the try-catch, there's no exception. Dumping `$response` doesn't change anything here. Calling `$response->getData();` does, however, throw the exception, but this is the method you should not use when adding contacts because the response is empty on success.

**Comment by Galyam** [comment]
ok, thanks
